# Generated by Django 5.1.1 on 2024-10-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        ('users', '0002_remove_user_workout_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
