# Generated by Django 5.1.1 on 2024-10-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutrition_user'),
        ('users', '0002_remove_user_workout_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
